<?php
/**
 * @file
 * level_2_v1_0_stage.features.uuid_bean.inc
 */

/**
 * Implements hook_uuid_features_default_beans().
 */
function level_2_v1_0_stage_uuid_features_default_beans() {
  $beans = array();

  $beans[] = array(
    'label' => 'resources page info',
    'description' => NULL,
    'title' => 'Resources',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'resources-page-info',
    'view_mode' => 'default',
    'created' => 1403762782,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => 'bc0839c2-e0a3-4f88-93e2-110df6d40e5d',
    'uuid' => '0382e379-693c-4aab-9493-1f7ea8679bce',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is a test line.',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'Our technology section page info',
    'description' => NULL,
    'title' => 'Our Technology',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'our-technology-section-page-info',
    'view_mode' => 'default',
    'created' => 1403763686,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => 'caeeaf5c-4e51-49e2-89cd-a085cc5cb989',
    'uuid' => '05e3cc03-cfb1-4515-a8cf-1ee16cbbf7fa',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is a test line.',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'In His Own Words Info',
    'description' => NULL,
    'title' => 'In His Own Words',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'in-his-own-words-info',
    'view_mode' => 'default',
    'created' => 1403762741,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => 'b5204295-f520-4cb3-ac49-91ffcfade6a3',
    'uuid' => '142cb40a-64c7-48bd-b4ec-9fdfa615a498',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is a test line',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is a test line',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is a test line',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'Behind the scenes section page info',
    'description' => NULL,
    'title' => 'Behind The Scenes',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'behind-the-scenes-section-page-i',
    'view_mode' => 'default',
    'created' => 1403763767,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '3c1889cb-ab5a-4a91-a31f-ab346e138b74',
    'uuid' => '3c584bc0-f267-44ad-9769-cb062612a405',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is a test line.',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'Livingstone Online Title',
    'description' => NULL,
    'title' => 'Livingstone Online',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'livingstone-online-title',
    'view_mode' => 'default',
    'created' => 1403673071,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '3285e6dd-0d74-4afe-bb13-1d17edde7b1b',
    'uuid' => '591d0e37-4f2f-4f13-87c5-705bac6f1e87',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is test line.
',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is a test line.
',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is a test line.',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'life and times section page info',
    'description' => NULL,
    'title' => 'Life & Times',
    'type' => 'section_title',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'life-and-times-section-page-info',
    'view_mode' => 'default',
    'created' => 1403762828,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '0ae66167-d109-4ddc-9d66-e69cf194f39d',
    'uuid' => '6c63c74f-8c02-48fb-894a-bc8aeb341010',
    'field_abstract' => array(
      'und' => array(
        0 => array(
          'value' => 'This is a test line.',
          'format' => 'full_html',
        ),
        1 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
        2 => array(
          'value' => 'This is test line.',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  $beans[] = array(
    'label' => 'Livingstone Header Info',
    'description' => NULL,
    'title' => 'LIVINGSTONE ONLINE',
    'type' => 'section_header',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'livingstone-header-info',
    'view_mode' => 'default',
    'created' => 1405596332,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '2fccdbe8-7faa-41d9-8a74-0a1588851ea2',
    'uuid' => '7d617351-64b1-4145-8651-dab8ab618bc0',
    'field_section_sub_title' => array(
      'und' => array(
        0 => array(
          'value' => 'THE WORDS OF EXPLORER DAVID LIVINGSTONE',
          'format' => 'full_html',
        ),
      ),
    ),
  );
  return $beans;
}
